# Site settings
title: LITE & SLIM
email: nuvitrin@gmail.com
description: "(주)라이트앤슬림 | 대표자.개인정보관리책임자:황세진 | 사업자등록번호: 200-88-74496 | 통신판매 신고번호:제 2014-서울강남-00673호 본사:서울특별시 강남구 도곡로 112 서한빌딩 2층 | 영업 및 물류센터: 서울특별시 강남구 학동로 201 구연빌딩 4층 (주)라이트앤슬"  
baseurl: /nuvitrin
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
