# Site settings
title: LITE & SLIM
email: jinny@litenslim.com
description: "(주)라이트앤슬림 | 대표자.개인정보관리책임자:황세진 | 사업자등록번호: 220-88-74496 | 통신판매 신고번호:제 2014-서울강남-00673호 | 본사: 서울특별시 강남구 학동로 201, 구연빌딩 4층 (주)라이트앤슬림 | 02-516-2332 (평일 오전9시~오후6시, 점심시간 11:30~12:30)"
baseurl: /nuvitrin
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
